import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// layout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      {/* min-h-screen -> garantir altura total
         flex flex-col -> empilhar os itens verticalmente
      */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <Header />

        {/* Componente <main> com 'flex-1' empurra o Footer para o final 
           da tela, ainda que a página tenha pouco conteúdo, não sendo necessário colocar os atributos "fixed bottom-0 left-0 w-full" direto no Footer.tsx
        */}
        <main className="flex-1">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
